# Generated by Django 3.0.2 on 2020-02-01 21:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcacao',
            name='data_marcacao',
            field=models.DateTimeField(default=django.utils.timezone.now, unique=True),
        ),
    ]
